version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: titanium_user
      POSTGRES_PASSWORD: titanium_pass
      POSTGRES_DB: titanium_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
