ALTER TABLE users ADD COLUMN IF NOT EXISTS eve_access_token TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS eve_refresh_token TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS token_expires_at TIMESTAMPTZ;
